# Generated by Django 5.0.4 on 2024-06-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReg',
            new_name='PatientReg',
        ),
        migrations.DeleteModel(
            name='AdminReg',
        ),
    ]
