# Generated by Django 5.0.4 on 2024-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_userreg_patientreg_delete_adminreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='fName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='lName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='uId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
