# Generated by Django 5.0.4 on 2025-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.CharField(blank=True, choices=[('Dermatologist', 'Dermatologist'), ('Cardiology', 'Cardiology'), ('Gynaecology', 'Gynaecology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(choices=[('Dr. Jeff Harvey', 'Dr. Jeff Harvey'), ('Dr. Steve Obroy', 'Dr. Steve Obroy'), ('Dr. Noa Blake', 'Dr. Noa Blake'), ('Dr. Alice Carter', 'Dr. Alice Carter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
